DELETE http://localhost:3003/api/blogs/68a86da197e5bb79b24ee342
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY4YTc3OGM1ZDQ2OGI1MzM0NTc4MmRiMCIsImlhdCI6MTc1NTgwNjc5NX0.o4QirF7eMidybCrTH37x4j8K8nbZ5d-VHXntwu9DSxE